sudo: required

language: php

dist: trusty

services:
  - docker

env:
  global:
    - IMAGE_NAME=nithinbenny444/nginxapp

notifications:
        email: nithinbenny444@gmail.com
os:
  - linux


before_deploy:
  # create a docker image tag for develop branch
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then export IMAGE_TAG=$TRAVIS_BUILD_NUMBER-dev; fi
  # create a docker image tag for git tags
  - if [[ $TRAVIS_TAG ]]; then export IMAGE_TAG=$TRAVIS_TAG; fi
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


deploy:
  # create docker image for develop or release branches
  - provider: script
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop.*
  # create docker image for tags
  - provider: script
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      tags: true


notifications:
  email:
    on_success: never
    on_failure: always
